import { levels } from '@/lib/levels'

// Every canned (non-AI) line in RWR lives here so the wording can be edited in one place.
// Rules that must survive edits: Todah is a guide, not a prophet. He never says a job or
// outcome is promised, and he does not roar until the player confirms their goal is reached.

export type EntryChoice = 'starting' | 'changing' | 'stuck' | 'curious'

export const lines = {
  title: {
    name: 'RWR',
    subtitle: '16-BIT CAREER ADVENTURE',
    powerOn: 'POWER ON',
    powerOnHint: 'Tap, click, or press any key',
    pressStart: 'PRESS START',
    skipHint: 'Tap or press any key to skip',
    continuePrompt: 'CONTINUE?',
    continueYes: 'CONTINUE',
    continueNew: 'NEW GAME',
    continueLions: 'MY LIONS',
    newGameConfirm: (lion: string) =>
      `Start fresh with a new lion? ${lion} is kept safe under MY LIONS, and you can come back any time.`,
    newGameYes: 'YES, START FRESH',
    newGameNo: 'KEEP PLAYING',
  },

  // Naming the lion for a new game, and the list of lions set aside from earlier games.
  lions: {
    nameQuestion: 'Do you want to rename your new lion?',
    nameLabel: "New lion's name",
    // Lion or lioness. The choice changes part of the wardrobe and nothing about the trail.
    sexLabel: 'Lion or lioness?',
    sexes: { male: 'LION', female: 'LIONESS' },
    sexNote: 'A lion grows a mane. A lioness grows an aura, and has essentials and bags of her own in the wardrobe. You can change this later in the wardrobe.',
    changeQuestion: 'Change your lion',
    changeLabel: "Lion's name",
    changeSave: 'SAVE',
    changeNote: 'Nothing you own is lost. Pieces that do not fit wait in the wardrobe until you switch back.',
    yours: (lion: string, kind: string) => `${lion} · ${kind}`,
    change: 'RENAME OR CHANGE',
    nameUse: 'USE THIS NAME',
    nameKeep: (lion: string) => `KEEP ${lion.toUpperCase()}`,
    nameCancel: 'CANCEL',
    listHeading: 'MY LIONS',
    listIntro: 'Each lion keeps its own trail. Pick one to carry on with it. The one you are playing now is kept too.',
    summary: (form: string, power: number, max: number) => `${form} · PRIDE POWER ${power}/${max}`,
    walkingWith: (player: string) => `Walking with ${player}`,
    goal: 'Main goal:',
    play: 'PLAY',
    close: 'CLOSE',
  },

  account: {
    signedInAs: (email: string) => `Signed in as ${email}`,
    logOut: 'LOG OUT',
  },

  settings: {
    // The one SETTINGS button in the corner, and the box it opens.
    open: 'SETTINGS',
    heading: 'SETTINGS',
    sound: 'SOUND',
    soundFull: 'FULL',
    soundLow: 'LOW',
    soundNone: 'OFF',
    tvNote: 'The old TV set is drawn round the game on a wide screen.',
    privacy: 'PRIVACY AND YOUR DATA',
    close: 'CLOSE',
    motionOn: 'MOTION: ON',
    motionOff: 'MOTION: OFF',
    // The old TV set drawn round the game on a wide screen.
    tvOn: 'TV SET: ON',
    tvOff: 'TV SET: OFF',
    toNight: 'Switch to night mode',
    toDay: 'Switch to day mode',
  },

  login: {
    heading: 'WHO GOES THERE?',
    tabLogin: 'LOG IN',
    tabSignup: 'SIGN UP',
    email: 'Email',
    password: 'Password',
    passwordHint: 'At least 8 characters.',
    submitLogin: 'LOG IN',
    submitSignup: 'CREATE ACCOUNT',
    guest: 'PLAY AS GUEST',
    close: 'CLOSE',
    working: 'One moment...',
    privacy:
      'Your game is saved in this browser only. An account stores your email with our login provider. Todah asks before any answer is sent to an AI service, and you can delete everything at any time.',
    privacyLink: 'How RWR handles your data',
    notConfigured: 'Accounts are not switched on yet. Guest mode works right now.',
    signupCheckEmail: 'Almost there. Check your email for a confirmation link, then log in.',
    genericError: 'That did not work. Check your email and password and try again.',
  },

  onboarding: {
    questName: 'QUEST 1: THE LAY OF THE LAND',
    next: 'NEXT',
    completeBanner: 'QUEST COMPLETE',
    hello: "Hey, traveler! I'm Todah. I'm still a cub, but I know every trail out here.",
    // Shown to every player before the first quest.
    ikigaiBrief:
      'Four circles mark this trail: Heart (what you love), Craft (what you are good at), Cause (what the world needs), and Coin (what can pay). Two ideas shaped it. The circles come from a Western picture of purpose. The spirit comes from Ikigai, a Japanese idea about the small things that make a day worth waking for. So that is what we look for: small, true moments.',
    ikigaiGotIt: 'GOT IT',
    ikigaiMore: 'TELL ME MORE',
    // The optional deeper explanation, one page per entry.
    ikigaiDeep: [
      'First influence: the four circles. They are a picture of purpose that Andres Zuzunaga drew in Spain in 2011. In 2014 a blogger, Marc Winn, wrote the Japanese word Ikigai in the middle, and off it went around the world. From it we took our shape: four circles, one level each.',
      'Where two circles meet, the picture gives a name: Passion, Mission, Vocation, Profession. Miss a circle and work can feel off. Paid but not in love: comfy, yet empty. In love but unpaid: joyful, yet broke. From this we took our map, which shows where your evidence is strong and where it is thin.',
      'Second influence: Ikigai itself (say ee-kee-guy). Iki is life, gai is worth. A garden. A grandchild. The first tea of the morning. Mieko Kamiya, a Japanese doctor, wrote the book on it in 1966. It lives in small things, never asks about pay, and does not have to be a job.',
      'From Ikigai we took our way of asking. Kamiya wrote that it has to be lived to be understood, so I ask about moments you have lived, not things you wish. Where we part ways: this game is about work and counts Coin. Ikigai is about a whole life. More on the ABOUT page.',
      `We walk one circle at a time: ${levels.map((level) => level.name).join(', ')}. I ask, you bring the evidence, and you decide what it means. I will never tell you what to be, and nothing here is a promise about any job.`,
    ],
    ikigaiNextPage: 'NEXT',
    ikigaiDone: 'READY',
    ikigaiSkip: 'SKIP',
    questIntro: 'Quest 1: The Lay of the Land. No wrong answers, no timer.',
    startQuest: 'START QUEST',
    whatIsThis: 'WHAT IS THIS?',
    explain:
      'RWR is a short game for thinking about work. We walk four circles, one at a time: what you love, what you are good at, who it helps, and what it can pay. At each one I ask for real moments from your life and we mark the evidence on a map. Then you set one goal of your own. I ask and you decide: I am a guide, not a fortune teller, and I will never tell you what to be.',
    explainContinue: 'GOT IT, START QUEST',
    askName: 'What should I call you?',
    nameLabel: 'Your name or nickname',
    namePlaceholder: 'Type a name',
    nameSubmit: 'OK',
    askEntry: (name: string) => `Good to meet you, ${name}. What brought you out here today?`,
    entryChoices: [
      { id: 'starting', label: 'Just starting out' },
      { id: 'changing', label: 'Changing careers' },
      { id: 'stuck', label: 'Feeling stuck' },
      { id: 'curious', label: 'Just curious' },
    ] as { id: EntryChoice, label: string }[],
    reactions: {
      starting: 'A fresh trail. Good. We get to look at everything with new eyes.',
      changing: 'Changing direction takes nerve. We will map where you have been before we pick a new path.',
      stuck: "Stuck is a real place on the map. We'll explore it together.",
      curious: 'Curious is the best reason there is. Let us wander a little and see what turns up.',
    } as Record<EntryChoice, string>,
    reactionContinue: 'KEEP GOING',
    consent:
      'Quick heads-up: to answer in my own words, I send what you type to an AI helper. Your name stays with me. Skip anything private, or pick trail notes and nothing leaves this device.',
    consentYes: 'USE AI REPLIES',
    consentNo: 'USE TRAIL NOTES ONLY',
    consentMore: 'PRIVACY DETAILS',
    thinking: 'Todah is thinking...',
    answerLabel: 'Your answer',
    answerPlaceholder: 'Type your answer',
    send: 'SEND',
    complete: (name: string) =>
      `Quest 1 complete. Thank you for walking with me, ${name}. Next is your trail map. We look for evidence in each of the four circles, starting with ${levels[0].name}: ${levels[0].circle}.`,
    toLevel: 'START LEVEL 1: HEART',
    change: 'CHANGE',
    changeLabel: 'Change this answer. Any questions after it are asked again.',
    back: 'BACK',
    backLabel: 'Back to the title screen. Your answers so far are kept.',
    toMap: 'OPEN MY TRAIL MAP',
    toUpgrades: 'SEE LION UPGRADES',
    toTitle: 'BACK TO TITLE',
  },

  // Used when no AI key is set, when the AI is unreachable, and in demo mode.
  // Same shape as the live quest: one warm-up question, then two follow-ups.
  scriptedFollowUps: [
    'Tell me about a recent day that felt good. What were you doing?',
    'Thanks for sharing that. What was it about that day that pulled you in?',
    'I hear you. If you could have one more hour of that day, which part would you pick?',
  ],

  errors: {
    aiUnavailable: 'My voice is a little faint right now, so I will stick to my trail notes.',
    aiCap: 'We have talked a lot this session. Let us rest here and pick the trail back up later.',
    aiDaily: 'We have talked a lot today, so I will use my trail notes from here. My own voice is back tomorrow.',
    emptyAnswer: 'Type something first. A few words are plenty.',
    nameBlocked: 'That name is not welcome on this trail. Please pick another one.',
  },

  privacy: {
    heading: 'YOUR DATA',
    intro: 'Some answers in RWR are personal. Here is exactly where they go, and how to remove them.',
    points: [
      { title: 'On this device', body: 'Your name, answers, trail map, upgrades, and goal are saved in this browser so you can come back, for the lion you are playing and any you have kept. Anyone who uses this browser profile could open them. Turn saving off below on a shared computer.' },
      { title: 'AI replies', body: 'If you choose AI replies, the answers you type are sent to an AI service to write what Todah says. Your name is not sent, and email addresses, links, and phone numbers are removed first. RWR does not log or store your answers on its server.' },
      { title: 'A fair share of the AI', body: 'The AI is free and shared by every player, so each browser gets a set number of AI replies a day. To count them, RWR keeps one small cookie in your browser. It holds a date and a number and nothing about you. After the limit, Todah carries on from written questions.' },
      { title: 'My Pride', body: 'Your pride card holds your first name, your lion, Pride Power, and your main goal if you leave that switched on. It travels inside the link or QR code you share. RWR does not store it and its server never sees it, but anyone who has the link can read it, so share it only with people you trust.' },
      { title: "A friend's witness", body: 'When you ask someone what they would come to you for, your first name and your lion\'s name travel inside the link you send, and their answer travels inside the link they send back. RWR does not send, store, or see either one. If you use AI replies, what they said (not their name) is shown to the AI during the Craft level.' },
      { title: 'The road', body: 'Your goal, the obstacle you name, your plan, and what you tell Todah about each experiment are saved on this device like your other answers. With AI replies on, they are sent to the AI service to write the plan and Todah\'s reply, with the same protections.' },
      { title: "Todah's note", body: 'When your goal is reached, Todah leaves you a note made from what you said along the way. With AI replies on, those words are sent to the AI service to write it, with the same protections. The note is saved on this device. If you save it as a picture or send it to someone, that is your choice and RWR is not involved.' },
      { title: 'Wardrobe ideas', body: 'If you send an idea for a new wardrobe piece, the words you type are emailed to the person who makes RWR, with whether your lion is a lion or a lioness. Email addresses, links, and phone numbers are removed first. Your name, your account, and your game are not sent. One small cookie counts the ideas this browser has sent today.' },
      { title: 'Accounts', body: 'If you sign up, your email is stored by our login provider. Your answers are not stored in our database. Deleting your data below removes the account too.' },
      { title: 'What RWR never does', body: 'No ads, no trackers, and no selling or sharing of your data.' },
    ],
    saveOn: 'SAVE ON THIS DEVICE: ON',
    saveOff: 'SAVE ON THIS DEVICE: OFF',
    saveOffNote: 'Saving is off. Your game lasts until you close or reload this tab.',
    aiOn: 'AI REPLIES: ON',
    aiOff: 'AI REPLIES: OFF',
    tipsOn: 'TIPS: ON',
    tipsOff: 'TIPS: OFF',
    deleteButton: 'DELETE MY DATA',
    deleteConfirm: 'Delete your game and every kept lion from this device? If you are signed in, your account is deleted too. This cannot be undone.',
    deleteYes: 'YES, DELETE IT',
    deleteNo: 'KEEP MY DATA',
    deleted: 'Done. Your game data is gone from this device.',
    deletedAccount: 'Done. Your game data is gone from this device and your account is deleted.',
    deleteFailed: 'Your device copy is deleted, but the account could not be reached. Please try again.',
    back: 'BACK TO TITLE',
    link: 'PRIVACY',
  },

  // For the Talk to Todah help chat (not built yet).
  help: {
    menuHeading: 'TALK TO TODAH',
    menu: [
      "I'm stuck on a question",
      'Explain the four circles to me',
      'Help me think through a career idea',
      'Help with my roadmap',
      'Just talk',
    ],
  },

  upgrades: {
    heading: 'LION UPGRADES',
    intro: 'Each part of Todah grows when you fill in the matching part of your resume.',
    locked: 'COMING SOON',
    empty: 'EMPTY',
    level: (n: number, max: number) => `LEVEL ${n}/${max}`,
    save: 'SAVE',
    cancel: 'CANCEL',
    askTodah: 'ASK TODAH TO PHRASE THIS',
    suggestionsHeading: 'Starting points you can edit:',
    levelUp: 'LEVEL UP!',
    todahLabel: (form: string) => `TODAH: ${form}`,
    power: (n: number, max: number) => `PRIDE POWER ${n}/${max}`,
    toWardrobe: 'WARDROBE',
    sparks: (n: number) => `SPARKS ${n}`,
    powerFrom: 'WHERE IT COMES FROM',
    powerParts: {
      slots: 'Upgrade levels',
      map: 'Trail map evidence',
      steps: 'Real-world trail steps',
      milestones: 'Milestones',
    },
    powerPart: (label: string, n: number, max: number) => `${label}: ${n}/${max}`,
    milestones: {
      quest: 'Finish Quest 1.',
      goal: 'Set your main goal.',
      claims: 'Write a claim in all four circles of the trail map.',
      cheer: 'Send a cheer to a friend.',
      roar: 'Reach your main goal and let Todah roar.',
    },
    formCub: 'CUB',
    formNomad: 'NOMAD',
    formLeader: 'PRIDE LEADER',
    leaderLocked: 'PRIDE LEADER: LOCKED',
    leaderLockedBody:
      'Todah roars only when you say your main goal is reached. No one else gets to decide that.',
    toRoar: 'GO TO MY GOAL',
    back: 'BACK TO TITLE',
    denHeading: 'Your lions and their paths:',
    denGoalMissing: 'No main goal yet',
    denEvidence: (score: number, max: number, needed: number) => `Evidence ${score}/${max} (needs ${needed})`,
    denCounts: 'COUNTS',
    denNotYet: 'NOT YET',
    denHint: 'To explore another path, choose NEW GAME on the title screen. This lion is kept under MY LIONS.',
    denClose: 'CLOSE',
    checkLevel: (n: number) => `LEVEL ${n}`,
    checkMet: 'done',
    checkOpen: 'not yet',
    trailHeading: 'From your trail, in your own words:',
    mapTitle: 'TRAIL MAP',
    mapScore: (score: number, max: number) => `TRAIL EVIDENCE ${score}/${max}`,
    mapBody: 'See how much evidence you have in each circle, and take one real-world step. Each step adds two Pride Power.',
    toMap: 'OPEN TRAIL MAP',
    // Helpful tips on the upgrades screen. One shows per visit, the first that fits the game
    // so far (see pickTip in UpgradesScreen). Players can switch them off, and back on under
    // PRIVACY.
    // A lioness has no mane, so on her the MANE upgrade goes by another name. It is the same
    // upgrade with the same levels.
    lioness: {
      name: 'AURA',
      growth: 'Her aura glows brighter through three levels.',
      tipStart: 'Tap AURA to begin. One sentence about who you are at work earns the first level.',
    },
    tipLabel: 'TIP',
    tipGotIt: 'GOT IT',
    tipTurnOff: 'TURN TIPS OFF',
    tips: {
      start: 'Tap MANE to begin. One sentence about who you are at work earns the first level.',
      quest: 'Todah stays a cub until Quest 1 is finished. You can pick it up from the title screen.',
      nomad: 'Start two parts and Todah grows from Cub to Nomad.',
      levels: 'Every part has three levels. Open one to see what the next level needs.',
      phrase: 'Stuck on wording? Open a part and tap ASK TODAH TO PHRASE THIS for starting points you can edit.',
      unpaid: 'Unpaid and volunteer work counts under PAWS. So does caring for family.',
      pride: 'PRIDE grows with real connections: friends who join and people you reach out to.',
      wardrobe: 'Cheers from friends and job interviews earn sparks. Spend them in the WARDROBE to dress your lion.',
      den: 'DEN grows with each career path you explore. A path is a lion with a main goal and evidence on its trail map.',
      map: 'Your TRAIL MAP shows how much evidence you have in each of the four circles, and one small step to test the thinnest.',
      goal: 'Set your main goal under GO TO MY GOAL. Only you decide when it is reached.',
      device: 'Everything here is saved in this browser only. On a shared computer, PRIVACY has a switch to turn saving off.',
    },
  },

  // The wardrobe: accessories bought with sparks. Sparks come from encouragement and from
  // landing interviews, never from money.
  wardrobe: {
    heading: 'WARDROBE',
    intro: 'Dress your lion. One piece from each group can be worn at a time.',
    sparks: (n: number) => `SPARKS ${n}`,
    earnHeading: 'HOW TO EARN SPARKS',
    earnCheer: (n: number) => `A cheer from a friend in your pride: +${n}, once per friend per day.`,
    earnInterview: (n: number) => `Landing a job interview: +${n}. Log it under MY PRIDE.`,
    earnLevel: (n: number) => `Walking a level with Todah and marking your map: +${n} each.`,
    earnStep: (n: number) => `Doing a real-world trail step: +${n} each.`,
    earnedSoFar: (levels: number, steps: number, cheers: number, interviews: number) =>
      `So far: ${levels} ${levels === 1 ? 'level' : 'levels'}, ${steps} ${steps === 1 ? 'trail step' : 'trail steps'}, ${cheers} ${cheers === 1 ? 'cheer' : 'cheers'} and ${interviews} ${interviews === 1 ? 'interview' : 'interviews'}.`,
    tryOn: 'TRY ON',
    tryOff: 'TAKE OFF',
    tryNote: 'Guests can try any piece on. To keep one, sign up and earn it.',
    toPride: 'OPEN MY PRIDE',
    categories: {
      fur: 'FUR',
      mane: 'MANE COLOR',
      essentials: 'ESSENTIALS',
      hat: 'HATS',
      shades: 'SHADES AND GLASSES',
      ears: 'EARS',
      neck: 'NECK',
      body: 'JACKETS',
      bag: 'BAGS',
      outfit: 'TRANSFORMATIONS',
    },
    notes: {
      fur: 'Fur changes the coat only. The mane keeps its own color, so to match a coat, pick the mane of the same name.',
      mane: 'A color changes only the color. The mane itself grows as the MANE upgrade levels up, starting with a crest on top at level 1. Every coat has a mane of the same name that completes its set.',
      essentials: 'Only a lioness carries these. They stand on the floor by her paws, and up to three can be out at once: the first at her left, the second at her right, a third in the middle. Put out a fourth and the first is put away.',
      bag: 'Bags are for a lioness.',
      hat: 'The newer pieces all come in the same reds, blues, greens and blacks, so a cap can match your scarf, your jacket, or nothing at all.',
      outfit: 'A transformation changes the whole lion and is worn alone: while it is on, your other pieces wait in the wardrobe. More about the shishi on the ABOUT page.',
    },
    // What a lioness reads in place of a note above. She has no mane to match.
    lionessNotes: {
      fur: 'Fur changes the whole coat.',
    },
    colourLabel: (name: string) => `Color: ${name}`,
    colours: {
      red: 'red',
      blue: 'blue',
      green: 'green',
      purple: 'purple',
      teal: 'teal',
      pink: 'pink',
      black: 'black',
      white: 'white',
      tan: 'tan',
      olive: 'olive',
      grey: 'gray',
      brown: 'brown',
      gold: 'gold',
      yellow: 'yellow',
      silver: 'silver',
      rose: 'rose gold',
      sunset: 'sunset',
      fire: 'fire',
      ocean: 'ocean',
    },
    items: {
      golden: 'Golden',
      snow: 'Snow',
      shadow: 'Shadow',
      ember: 'Ember',
      rose: 'Rose',
      sky: 'Sky',
      'mane-natural': 'Natural',
      'mane-snow': 'Snow',
      'mane-shadow': 'Shadow',
      'mane-ember': 'Ember',
      'mane-rose': 'Rose',
      'mane-sky': 'Sky',
      'mane-white': 'White',
      'mane-purple': 'Purple',
      'mane-teal': 'Teal',
      cap: 'Cap',
      beanie: 'Beanie',
      explorer: 'Explorer hat',
      crown: 'Crown',
      shades: 'Shades',
      aviators: 'Aviators',
      sunset: 'Sunset shades',
      'glasses-round': 'Round glasses',
      'glasses-square': 'Square glasses',
      bandana: 'Trail bandana',
      scarf: 'Scarf',
      'bow-tie': 'Bow tie',
      chain: 'Lion chain',
      'cuban-chain': 'Cuban chain',
      'lion-cap': 'Lion cap',
      'head-bandana': 'Silk bandana',
      'shield-shades': 'Shield shades',
      'hoop-earrings': 'Hoop earrings',
      'hoop-earring': 'One hoop earring',
      perfume: 'Perfume',
      passport: 'Passport',
      wallet: 'Wallet',
      phone: 'Phone',
      'aviator-jacket': 'Aviator jacket',
      'indigo-jacket': 'Indigo jacket',
      'micro-bag': 'Micro bag',
      shishi: 'Shishi guardian',
    },
    price: (n: number) => `${n} SPARKS`,
    free: 'FREE',
    owned: 'YOURS',
    buy: 'BUY',
    wear: 'WEAR',
    takeOff: 'TAKE OFF',
    wearing: 'WEARING',
    short: (n: number) => `${n} more sparks needed`,
    needsPower: (n: number) => `Unlocks at Pride Power ${n}`,
    needsMane: (n: number) => `Unlocks when the MANE upgrade reaches level ${n}`,
    gifts: {
      quest: 'A gift for finishing Quest 1',
      nomad: 'A gift when Todah becomes a Nomad',
      leader: 'A gift when Todah roars',
    },
    bought: (name: string) => `${name} is yours.`,
    accountNote: 'Accessories are for players with an account. Sign up to dress your lion. Everything you have done so far stays.',
    accountButton: 'SIGN UP OR LOG IN',
    accountNeeded: 'Needs an account',
    back: 'BACK TO UPGRADES',
    // Ideas for new pieces, emailed to the maker (app/api/suggest). The form is shown only
    // when the server has a mailbox to send from.
    suggest: {
      heading: 'WHAT SHOULD WE ADD?',
      intro: 'Is there a piece you wish your lion could wear? Say what it is and it goes to the person who makes RWR.',
      label: 'Your idea',
      placeholder: 'A varsity jacket, in green...',
      send: 'SEND MY IDEA',
      sending: 'SENDING...',
      sent: 'Sent. Thank you.',
      empty: 'Write your idea first.',
      blocked: 'Please say that another way. Some words cannot be sent.',
      daily: 'That is all the ideas for today. Come back tomorrow with more.',
      failed: 'That did not send. Please try again in a moment.',
      fine: 'Only your words, and whether your lion is a lion or a lioness, are sent. No name, no email, and nothing from your game.',
    },
  },

  // The lookbook: every wardrobe piece in every colour, to look through.
  lookbook: {
    heading: 'LOOKBOOK',
    intro: 'Every piece in the wardrobe, in every color it comes in. One from each group can be worn at a time.',
    maneLevel: (n: number) => `Mane level ${n}`,
    only: { male: 'LION ONLY', female: 'LIONESS ONLY' },
    setsHeading: 'MATCHING SETS',
    setsIntro: 'Every coat has a mane of the same name. They are two pieces, found under FUR and MANE COLOR, and any coat can be worn with any mane.',
    open: 'SEE EVERY PIECE',
    back: 'BACK TO WARDROBE',
  },

  // The level interviews. Each level opens with a scripted question, then three follow-ups
  // (from the AI, or from `scripted` when the AI is off or down), then a claim and its
  // evidence go on the trail map. Rules that must survive edits: Todah asks for real moments,
  // never grades an answer, and never says what the answers mean for a career.
  level: {
    locked: 'Walk Quest 1 with me first, so I know what to call you.',
    toQuest: 'GO TO QUEST 1',
    progress: (done: number, total: number) => `Level progress: ${done} of ${total}`,
    summing: 'Todah is marking the map...',
    reviewHeading: 'WHAT TODAH HEARD',
    review: (name: string) =>
      `Here is what I heard, ${name}. It goes on your trail map, so change anything that is not right. It is your map, not mine.`,
    reviewScripted: (name: string) =>
      `Now put it in your own words, ${name}. One sentence below, then check only what is true. It goes on your trail map.`,
    emptyClaim: 'Write one sentence first, so the evidence has something to back.',
    save: 'MARK MY MAP',
    again: 'ANSWER AGAIN',
    replay: 'WALK THIS LEVEL AGAIN',
    replaceNote: 'This replaces what your trail map says for this circle now.',
    done: (name: string, score: number, max: number) =>
      `Marked, ${name}. This circle has ${score} of ${max} evidence. Whatever the number, it is a place to start from, not a grade.`,
    sparks: (n: number) => `+${n} SPARKS FOR THE WARDROBE`,
    toClaws: 'ADD THIS SKILL TO CLAWS',
    inClaws: 'ADDED TO CLAWS. OPEN UPGRADES TO GIVE IT PROOF.',
    toCrossroads: 'ON TO THE CROSSROADS',
    aiNote:
      'One more thing worth checking outside your own head: how AI is changing this kind of work. I will not guess at that, and nobody can promise you an answer, but people doing the work today can tell you what has changed for them.',
    toMap: 'OPEN MY TRAIL MAP',
    toUpgrades: 'SEE LION UPGRADES',
    fromMap: 'WALK THIS LEVEL WITH TODAH',
    back: 'BACK',
    backLabel: 'Back to the trail map. Your answers so far are kept.',
    next: (level: string) => `ON TO ${level}`,
    allDone: 'All four circles are walked. Your trail map shows where the evidence is strong and where it is thin.',
    circles: {
      heart: {
        name: 'LEVEL 1: HEART',
        banner: 'LEVEL 1 COMPLETE',
        start: 'START LEVEL 1',
        intro:
          'Level 1: Heart. This one is about what you love. Four questions, no wrong answers, no timer. I will ask for real moments, because one moment tells me more than a wish does.',
        opener: 'Think of the last time you lost track of time doing something. What were you doing?',
        scripted: [
          'When did you last do that? A rough date is fine.',
          'Do you ever do it when nobody is paying you or watching? Tell me about one time.',
          'Everything we love has dull parts. What is the dull part of this, and how do you feel about it on those days?',
        ],
        scriptedClose: 'Thank you. That is plenty to mark the map with.',
      },
      craft: {
        name: 'LEVEL 2: CRAFT',
        banner: 'LEVEL 2 COMPLETE',
        start: 'START LEVEL 2',
        intro:
          'Level 2: Craft. This one is about what you are good at, which is not always what you love. Four questions again. Small things count, so do not be modest with me.',
        opener: 'Tell me about something you did well lately. Something you were a little proud of.',
        scripted: [
          'Does anyone come to you for help with that? Who, and what do they ask for?',
          'What is one thing you made, fixed, or improved with that skill that you could point to?',
          'How long have you been doing it? A rough guess is fine.',
        ],
        scriptedClose: 'Thank you. Skill leaves tracks, and you just showed me some.',
      },
      cause: {
        name: 'LEVEL 3: CAUSE',
        banner: 'LEVEL 3 COMPLETE',
        start: 'START LEVEL 3',
        intro:
          'Level 3: Cause. This one is about who your work is for. Nobody can tell you what the world needs, so we start with real people you have already helped.',
        opener: 'Think of a time your work or your help made things easier for someone. Who was it, and what did you do?',
        scripted: [
          'Who would you most want your work to help? A person or a group, as plainly as you can name them.',
          'Has anyone asked you for that kind of help, or thanked you for it? Tell me about one time.',
          'Have you checked anywhere outside your own head that the need is real? A report, some numbers, or asking the people themselves all count.',
        ],
        scriptedClose: 'Thank you. A need with a face on it is easier to walk toward.',
      },
      coin: {
        name: 'LEVEL 4: COIN',
        banner: 'LEVEL 4 COMPLETE',
        start: 'START LEVEL 4',
        intro:
          'Level 4: Coin. This one is about what you can be paid for. I cannot promise anyone a job or a wage, and I will not guess at numbers. We only look at what you already know and what is worth looking up.',
        opener: 'What is one kind of work you could picture someone paying you for?',
        scripted: [
          'Do you know of real people, job titles, or businesses that are paid for that work today? Name one if you can.',
          'Have you ever been paid for it yourself, even once, even a little?',
          'Have you looked up what it pays? If you have, would it cover what you need?',
        ],
        scriptedClose: 'Thank you. Coin is the circle most worth checking outside your own head, and now you know what to check.',
      },
    },
  },

  // The Crossroads: a look across the four circles, then the player sets their own goal.
  // Rules that must survive edits: Todah names what he notices and hands the meaning back. He
  // never names a career, never ranks the circles, and never promises an outcome.
  crossroads: {
    name: 'THE CROSSROADS',
    intro: (name: string) =>
      `This is the Crossroads, ${name}. Four circles, laid side by side. I will tell you what I notice. What it means is yours to say.`,
    locked: 'The Crossroads opens once all four circles have a claim. Here is what is left to walk:',
    walk: (level: string) => `WALK ${level}`,
    circlesHeading: 'YOUR FOUR CIRCLES',
    thinking: 'Todah is looking across the map...',
    noticeHeading: 'WHAT TODAH NOTICES',
    // Used when the AI is off or down. Built from the map alone.
    scripted: (strongest: string, thinnest: string | null) =>
      thinnest && thinnest !== strongest
        ? `Your strongest evidence is in ${strongest}, and the least tested circle so far is ${thinnest}. Not tested yet is not the same as wrong. What do you make of that gap?`
        : `Your evidence is even across the circles, with ${strongest} a little ahead. When you lay the four side by side, what do you notice?`,
    scriptedEmpty: 'You have a claim in every circle, and none of them is tested yet. That is an honest place to stand. Which one would you most like to test first?',
    // Three paths: ideas to test, never answers. Choosing one makes its first milestone the
    // main goal, which is the goal the roar waits for. Rules that must survive edits: no path
    // is called right, likely, well paid or in demand, and the player can always write their own.
    pathsHeading: 'THREE PATHS TO TEST',
    pathsIntro:
      'Want to see where these four circles could point? I can lay out three kinds of work: the one closest to where you stand, one next door, and a bigger leap. Each is real work people make a living at. They are ideas to test, not answers, and I cannot promise where any of them leads.',
    pathsAsk: 'SHOW ME THREE PATHS',
    pathsThinking: 'Todah is reading the trail ahead...',
    pathsKinds: { near: 'THE PATH YOU ARE ON', next: 'THE PATH NEXT DOOR', wild: 'THE BIGGER LEAP' },
    pathsGoal: 'A goal to walk toward:',
    // Pay is a rough range and is always called that. Rules that must survive edits: it is
    // never shown as current or exact, and the link to current figures sits right under it.
    pathsPay: 'Rough pay:',
    pathsPayRange: (low: number, high: number) => `$${low.toLocaleString('en-US')} to $${high.toLocaleString('en-US')} a year`,
    pathsCheck: 'SEE CURRENT PAY AND WHAT IT TAKES',
    pathsCheckNote: 'The pay shown is a rough national range from older figures. It may be out of date, and it differs a lot by place. Each link opens O*NET OnLine, a free United States government site, with current pay for your area, the training the work takes, and its outlook. Look there before you choose.',
    pathsChoose: 'TAKE THIS PATH',
    pathsChosen: 'YOUR PATH',
    pathsAfter: 'Take one and its goal becomes your main goal. You can change the words after, or skip these and write your own below.',
    pathsFailed: 'I could not see the paths clearly just now. Here are three questions to find them yourself.',
    pathsCare: 'Before we look at paths: what you wrote sounds heavy, and that matters more than any goal. Please talk to someone you trust, or a professional, today. The trail will wait for you.',
    // Shown in place of the three paths when the AI is off or down.
    pathsOwn: [
      'The path you are on: what full-time work is closest to what you already do and have evidence for?',
      'The path next door: where else could the same strengths earn a living, somewhere you have not tried?',
      'The bigger leap: what would you train for if you gave yourself a few years?',
    ],
    goalThinking: 'Todah is thinking about your goal...',
    goalNext: 'Next we plan the first stretch of road.',
    goalHeading: 'YOUR MAIN GOAL',
    // Two things the four-circle picture gets wrong if it is read too literally. Both are
    // backed by research (see docs/architecture/overview.md), so keep them true if reworded.
    beforeGoal:
      'Two things before you choose. The four circles do not all have to live in one job: plenty of people find Heart in one place and Coin in another. And a thin circle is not a no. It only means not tested yet, and what we love and what we are good at both grow with doing.',
    goalIntro:
      'Now pick one goal to walk toward. Make it something you will know you have reached, and make it yours. Todah roars only when you say it is done.',
    goalLabel: 'My main goal',
    goalPlaceholder: 'For example: get paid for my first bookkeeping job',
    goalSave: 'SET MY GOAL',
    goalChange: 'CHANGE MY GOAL',
    goalSet: (goal: string) => `Your main goal: ${goal}`,
    goalBlocked: 'Write the goal first. One plain sentence is plenty.',
    done: (name: string) =>
      `That is a goal worth walking toward, ${name}. I cannot promise where the trail leads, but I will be here when you get there. Next we plan the first stretch of road.`,
    toRoad: 'PLAN THE ROAD',
    toRoar: 'GO TO THE ROAR',
    toUpgrades: 'BUILD MY LION',
    toMap: 'BACK TO MY TRAIL MAP',
  },

  // The About page. Rules that must survive edits: credit the four circles to the people who
  // drew them, never present them as Japanese, and never claim the game teaches ikigai.
  about: {
    chip: 'ABOUT',
    heading: 'ABOUT RWR',
    sections: [
      {
        title: 'WHAT THIS IS',
        body: [
          'RWR is a short, free game for thinking about work. A lion cub called Todah asks about real moments from your life, and together you mark the evidence on a map: what you love, what you are good at, who it helps, and what it can pay. Then you set one goal of your own. Todah roars only when you say you have reached it.',
          'It is a place to think, not a test. At the Crossroads Todah can lay out three paths to test if you ask, but he does not choose for you, and he never promises a job or any outcome.',
        ],
      },
      {
        title: 'WHAT THE AI DOES',
        body: [
          'If you allow it, an AI service writes what Todah says. It asks and reflects back. You bring the evidence and decide what it means, and you can change every word before it is marked on your map.',
          'It is told never to tell you what to be, never to guess at pay or your chances, and to respond with care if you are having a hard time. Without it, the whole game runs from written questions and nothing you type leaves your device.',
        ],
      },
      {
        title: 'WHAT SHAPED RWR',
        body: [
          'The purpose diagram gave RWR its shape. Its four circles became four levels (Heart, Craft, Cause, Coin), and its overlaps became the trail map, which shows where your evidence is strong and where it is thin.',
          'Ikigai gave RWR its way of asking. It is a Japanese idea about what makes life worth living, found in small, ordinary things. So Todah asks about small moments you have actually lived, and the map counts what you have done, not what you wish.',
          'Old 16-bit adventure games gave RWR its heart: a companion who grows as you do, and a journey you take at your own pace.',
        ],
      },
      {
        title: 'A SHORT HISTORY OF THE DIAGRAM',
        body: [
          'The four circles were drawn in 2011 by Andres Zuzunaga, a Spanish writer, as a diagram of purpose: what you love, what you are good at, what the world needs, and what you can be rewarded for. It first appeared in print in 2012, in a book by Borja Vilaseca.',
          'In 2014 a blogger, Marc Winn, replaced the word "purpose" in the middle with the Japanese word "ikigai". That version spread around the world, and many people now think the diagram is an old Japanese idea. It is not, so the middle of ours says PURPOSE, the word its author put there.',
        ],
      },
      {
        title: 'IKIGAI IN JAPAN',
        body: [
          'Ikigai joins iki, life, and gai, worth. For many people in Japan it is something small and daily: family, a craft, a garden, a morning routine. It can be work, but it does not have to be, and it has nothing to do with being paid.',
          'The best-known writing on it is the 1966 book Ikigai-ni-tsuite by Mieko Kamiya, a psychiatrist. She described the things that give a life meaning and the feeling itself that life is worth living, and wrote that it has to be lived to be understood.',
          'RWR is influenced by ikigai. It does not teach it. Ours is about work and counts pay, and ikigai is about a whole life. If we have described it badly, we would like to be corrected.',
        ],
      },
    ],
    credit: 'Made by cohortjuan',
    creditUrl: 'https://github.com/cohortjuan',
    // Shown under the sections above. Keep it true and plain: the shishi is not ours.
    shishi: {
      title: 'THE SHISHI',
      body: [
        'One outfit turns your lion into a shishi. Guardian lions stand in pairs at gates and temples across East Asia: shi in China, where they come from, and shishi or komainu in Japan. In the lion dance, a shishi chases off bad luck and brings in good.',
        'Ours is green with gold curls. Green is the cloth of the Japanese lion dance, shishi-mai.',
        'Todah is a lion, and this one is here as a salute to those lions, not as a joke at their expense. If we have drawn or described it badly, we would like to be told.',
      ],
    },
    sourcesHeading: 'WHERE TO READ MORE',
    sources: [
      { label: 'Ikigai (Wikipedia)', url: 'https://en.wikipedia.org/wiki/Ikigai' },
      { label: 'Mieko Kamiya and Ikigai-ni-tsuite (Ikigai Tribe)', url: 'https://ikigaitribe.com/blogpost/ikigai-ni-tsuite/' },
      { label: 'The Venn diagram of purpose and its history (Ikigai Tribe)', url: 'https://ikigaitribe.com/blogpost/the-venn-diagram-of-purpose/' },
    ],
    toPrivacy: 'HOW RWR HANDLES YOUR DATA',
    back: 'BACK TO TITLE',
  },

  // The road: what might get in the way, an if-then plan for it, and three small experiments.
  // Rules that must survive edits: the plan and the steps are the player's to change, a result
  // they did not hope for is never called a failure, and nothing here promises an outcome.
  road: {
    name: 'THE ROAD',
    noGoal: 'The road starts from a goal. Set yours at the Crossroads first.',
    toCrossroads: 'GO TO THE CROSSROADS',
    goal: (goal: string) => `Your main goal: ${goal}`,
    askObstacle: (name: string) =>
      `Every road has a rough patch, ${name}. Looking at your goal honestly, what is most likely to get in your way?`,
    obstacleLabel: 'What might get in the way',
    obstaclePlaceholder: 'For example: I run out of energy after work',
    obstacleSend: 'PLAN FOR IT',
    obstacleEmpty: 'Name one thing first. A few words are plenty.',
    thinking: 'Todah is sketching the road...',
    // Shown instead of a plan when what the player wrote sounds like real distress.
    care: (name: string) =>
      `That sounds heavy, ${name}, and I am glad you said it. The road can wait. If it would help, talk to someone you trust, or to a professional, about how you are feeling. I will be here whenever you want to come back.`,
    careLater: 'COME BACK LATER',
    careAnyway: 'PLAN IT MYSELF',
    review: (name: string) => `Here is a first sketch, ${name}. Change any line until it sounds like you.`,
    reviewScripted: (name: string) =>
      `Here is a starting sketch, ${name}. Finish the plan in your own words, and change any step that does not fit.`,
    planHeading: 'IF IT GETS ROUGH',
    planLabel: 'My plan for the rough patch',
    planPlaceholder: 'If ..., then I will ...',
    planHint: 'One sentence: "If [the thing in my way] happens, then I will [one small thing I can do]."',
    stepsHeading: 'THREE SMALL EXPERIMENTS',
    stepsIntro: 'Small things to try this week. Each one tests a circle out in the real world.',
    stepLabel: (n: number, circle: string) => `Experiment ${n}, tests ${circle}`,
    tests: (circle: string) => `Tests ${circle}`,
    save: 'SET MY ROAD',
    saveBlocked: 'Write your plan and at least one experiment first.',
    set: (name: string) =>
      `That is your road, ${name}. Try one experiment, then come back and tell me how it went. I will be here either way.`,
    did: 'I DID THIS',
    howHeading: 'HOW DID IT GO?',
    howLabel: 'What happened',
    howPlaceholder: 'A few honest sentences. It does not have to have gone well.',
    howSend: 'TELL TODAH',
    howCancel: 'NOT YET',
    howEmpty: 'Tell me a little about what happened first.',
    listening: 'Todah is listening...',
    checkinScripted: 'Thank you for telling me. Whatever happened, you know something now that you did not know before.',
    mapChanged: (circle: string) => `Has anything changed for ${circle}? Check only what is true now.`,
    doneOn: (date: string) => `Done ${date}`,
    youSaid: 'You said:',
    power: '+2 PRIDE POWER',
    again: 'PLAN THE ROAD AGAIN',
    againConfirm: 'Plan the road again? Your plan and experiments are replaced, along with what you told Todah about them.',
    againYes: 'YES, PLAN AGAIN',
    againNo: 'KEEP THIS ROAD',
    toUpgrades: 'BUILD MY LION',
    toMap: 'OPEN MY TRAIL MAP',
    toRoar: 'GO TO THE ROAR',
  },

  // A friend's witness: someone who knows the player says what they would come to them for.
  // It travels in links, like a cheer. RWR never sends or sees it.
  witness: {
    name: 'A FRIEND\'S WITNESS',
    intro:
      'What you are good at is easier to see from outside. Ask one person who knows you a single question, and what they say is kept beside your Craft circle.',
    needName: 'Walk Quest 1 first, so the link can carry your name.',
    toQuest: 'GO TO QUEST 1',
    yourLink: 'YOUR QUESTION LINK',
    question: (name: string) => `What would you come to ${name} for?`,
    sendNote: 'Send this link to someone who knows your work or your help. They need no account and no game of their own.',
    copy: 'COPY MY LINK',
    copied: 'Link copied. Send it to someone who knows you.',
    copyFailed: 'Copying did not work here. Select the link below and copy it by hand.',
    pasteHeading: 'GOT AN ANSWER?',
    pasteIntro: 'Open the link they send back, or paste it here.',
    pasteLabel: 'Their answer link',
    pasteAdd: 'ADD THEIR ANSWER',
    bad: 'That does not look like an answer link.',
    notYours: 'That answer was written for a different lion.',
    own: 'This is your own question link. Send it to someone else to answer.',
    added: (name: string) => `Kept. Thank ${name} when you can.`,
    already: 'You already have that answer.',
    heardHeading: 'WHAT PEOPLE SAID',
    none: 'Nothing yet. Answers appear here when they come back.',
    said: (name: string) => `${name} would come to you for:`,
    honour: 'This is the honor system: RWR cannot check who wrote an answer. It only means something if it is real.',
    // What the friend sees.
    askedBy: (name: string, lion: string) =>
      `${name} is using RWR, a small game for thinking about work, with a lion called ${lion}. They are asking a few people who know them one question.`,
    answerLabel: 'Your answer',
    answerPlaceholder: 'For example: untangling a problem nobody else has the patience for',
    answerName: 'Your first name',
    answerMake: 'MAKE MY ANSWER LINK',
    answerEmpty: 'Write an answer and your first name first.',
    answerBlocked: 'Something in that cannot be used. Try different words.',
    answerReady: (name: string) => `Thank you. Now send this link back to ${name}. RWR does not send it for you and never sees it.`,
    answerCopy: 'COPY THE LINK',
    answerCopied: 'Link copied. Send it back to them.',
    privacy: 'Your answer travels inside the link itself. Nothing you type here is sent to RWR or stored by it.',
    onMap: 'People who know you would come to you for:',
    ask: 'ASK SOMEONE WHO KNOWS YOU',
    back: 'BACK TO MY TRAIL MAP',
    toTitle: 'SEE WHAT RWR IS',
  },

  // Todah's note: the final gift, left "on the table" once the goal is reached. Rules that must
  // survive edits: it is built from the player's own words, it lifts them up for things they
  // actually did, and it never gives advice or promises what happens next.
  letter: {
    name: "TODAH'S NOTE",
    locked: 'I leave my note when you tell me your goal is reached. Not before.',
    toRoar: 'GO TO THE ROAR',
    waiting: (name: string) => `One more thing, ${name}. I left something on the table for you.`,
    open: 'OPEN THE NOTE',
    writing: 'Todah is writing...',
    dear: (name: string) => `Dear ${name},`,
    signoff: 'Your friend,',
    kept: 'This note is kept with your lion. You can read it again any time from the roar screen.',
    save: 'SAVE AS A PICTURE',
    send: 'SEND IT TO SOMEONE',
    saved: 'Saved as a picture.',
    saveFailed: 'The picture could not be made here. A screenshot will do the job.',
    again: 'ASK TODAH TO WRITE IT AGAIN',
    againLeft: (n: number, sex: 'male' | 'female') =>
      `${sex === 'female' ? 'She' : 'He'} will write it ${n === 1 ? 'once more' : `${n} more times`}.`,
    back: 'BACK TO THE ROAR',
    credit: 'RWR: 16-bit Career Adventure',
    shareTitle: (lion: string) => `A note from ${lion}`,
    fileName: 'a-note-from-todah.jpg',
    // Read out in place of the picture, and offered as plain text under it.
    alt: (lion: string) => `A handwritten note from ${lion}, left on a wooden desk, with a photo of your lion taped to it. It reads:`,
    asText: 'READ IT AS PLAIN TEXT',
    drawing: 'Todah is finding a pen...',
    onRoar: "READ TODAH'S NOTE",
    // The note without the AI: the player's own words, set in order. Each line is used only
    // if the player said that thing.
    scripted: {
      startWarmup: (words: string) => `When we met, I was a cub, and you told me about a good day: "${words}"`,
      startPlain: 'When we met, I was a cub and you were only starting down this trail.',
      heart: (words: string) => `You told me, "${words}".`,
      witness: (name: string, words: string) => `${name} said they would come to you for "${words}".`,
      goal: (words: string) => `Then you set a goal that was all yours: "${words}".`,
      obstacle: (words: string) => `You knew what would get in the way: "${words}". You made a plan for it anyway.`,
      experiment: (words: string) => `You went out and tried something real, and came back to tell me: "${words}"`,
      close: 'And then you did it. Nobody did that for you. I only walked beside you.',
      sendoff: 'Head up. You earned this one.',
    },
  },

  // Forgotten passwords: asking for a reset link, and choosing the new password.
  reset: {
    forgot: 'Forgot password?',
    heading: 'RESET PASSWORD',
    intro: 'Type the email you signed up with. A link to choose a new password will be sent to it.',
    send: 'SEND RESET LINK',
    backToLogin: 'BACK TO LOG IN',
    sent: 'If that email has an account, a reset link is on its way. Check your inbox and your spam folder.',
    failed: 'That did not work. Wait a minute and try again.',
    change: 'CHANGE PASSWORD',
    changeSent: (email: string) => `A link to choose a new password is on its way to ${email}.`,
    newHeading: 'NEW PASSWORD',
    newIntro: 'Choose a new password for your account.',
    newLabel: 'New password',
    newHint: 'At least 8 characters.',
    save: 'SAVE PASSWORD',
    saved: 'Your password is changed, and you are logged in.',
    close: 'CLOSE',
    working: 'One moment...',
  },

  // Dev tools: shown only to an account flagged as a dev account.
  dev: {
    chip: 'DEV',
    heading: 'DEV TOOLS',
    intro: 'For showing and testing the game without playing up to each stage. These change how this lion looks and what it can wear. They never add to Pride Power.',
    checking: 'Checking your account...',
    locked: 'This page is for a dev account. Log in with one to use it.',
    lookHeading: 'THIS LION',
    unlockOn: 'EVERY ACCESSORY: UNLOCKED',
    unlockOff: 'EVERY ACCESSORY: AS EARNED',
    maneHeading: 'MANE SIZE',
    formHeading: 'FORM',
    auto: 'AS EARNED',
    maneLevel: (n: number) => (n === 0 ? 'CUB TUFT' : `LEVEL ${n}`),
    roarHeading: 'THE ROAR',
    roarOn: 'GOAL REACHED: YES',
    roarOff: 'GOAL REACHED: NO',
    roarNote: 'Switches the reward screen and the crown on or off for this lion.',
    demoGoal: 'Demo goal: land my first job in my new field',
    screensHeading: 'JUMP TO A SCREEN',
    screens: {
      '/': 'TITLE',
      '/quest': 'QUEST 1',
      '/level/heart': 'LEVEL 1',
      '/level/craft': 'LEVEL 2',
      '/level/cause': 'LEVEL 3',
      '/level/coin': 'LEVEL 4',
      '/crossroads': 'CROSSROADS',
      '/road': 'THE ROAD',
      '/witness': 'WITNESS',
      '/letter': "TODAH'S NOTE",
      '/upgrades': 'UPGRADES',
      '/map': 'TRAIL MAP',
      '/pride': 'MY PRIDE',
      '/wardrobe': 'WARDROBE',
      '/lookbook': 'LOOKBOOK',
      '/roar': 'ROAR',
      '/privacy': 'PRIVACY',
      '/about': 'ABOUT',
    },
    off: 'TURN DEV TOOLS OFF',
    offNote: 'Puts this lion back to what it has earned.',
  },

  // The trail map: evidence for each of the four circles. Rules that must survive edits: it is a
  // map, not a verdict. It never names a best career and never promises an outcome.
  map: {
    heading: 'TRAIL MAP',
    intro: 'Purpose, for work, sits where four circles meet. This map shows how much evidence you have in each one. It is a map, not a verdict: only you decide where to walk.',
    score: (score: number, max: number) => `TRAIL EVIDENCE ${score}/${max}`,
    circleScore: (score: number, max: number) => `${score}/${max}`,
    empty: 'Each circle is filled in by walking its level with Todah. Start with Heart.',
    walkFirst: 'Nothing here yet. Walk this level and what you say is marked here, for you to change afterward.',
    walkAgain: 'WALK THIS LEVEL AGAIN',
    crossroads: 'All four circles have a claim. The Crossroads is where you look across them and set a goal.',
    toCrossroads: 'GO TO THE CROSSROADS',
    strongest: (circle: string) => `Strongest evidence so far: ${circle}.`,
    thinnest: (circle: string) => `Thinnest evidence so far: ${circle}.`,
    full: 'Every circle has full evidence. Walk it for a while and come back when something changes.',
    nextStep: 'ONE SMALL STEP',
    claimHint: 'Write a claim first. Evidence counts once there is something to back.',
    evidenceHeading: 'Check only what is true:',
    fromQuest: 'From Quest 1, you told Todah:',
    needsHeading: (max: number) => `Pick up to ${max} needs you care about most:`,
    needsSource: "The list is the United Nations' 17 Sustainable Development Goals.",
    outsideHeading: 'Check it outside your own head:',
    outsideNote: 'These are United States sources. If you live elsewhere, look for your own country\'s labor statistics.',
    stepsHeading: 'TRAIL STEPS',
    stepsIntro: 'Small things to do out in the world. Check one off when you have really done it. Each adds two Pride Power.',
    stepDone: 'I DID THIS',
    stepUndo: 'DONE. UNDO?',
    stepFor: (circle: string) => `Tests ${circle}`,
    stepForAll: 'Makes it real',
    back: 'BACK TO UPGRADES',
    circles: {
      heart: {
        question: 'What do you love doing?',
        placeholder: 'For example: working out why something is broken and fixing it',
        evidence: {
          recent: 'I did it in the last month.',
          unpaid: 'I do it even when nobody pays me or is watching.',
          boring: 'I still like it on the boring days.',
        },
        step: 'Spend 30 minutes on it this week with nobody watching. Afterward, notice whether you wanted more.',
      },
      craft: {
        question: 'What are you good at?',
        placeholder: 'For example: explaining technical problems in plain words',
        evidence: {
          asked: 'People come to me for help with this.',
          made: 'I can point to something I made, fixed, or improved.',
          practiced: 'I have practiced it for a year or more.',
        },
        step: 'Ask one person who has seen your work what they would come to you for.',
      },
      cause: {
        question: 'Who or what do you want your work to help?',
        placeholder: 'For example: people who are stuck with tools nobody explained to them',
        evidence: {
          named: 'I can name a real person or group this helps.',
          thanked: 'Someone has asked me for this, or thanked me for it.',
          checked: 'I checked a source outside my own head and the need is real.',
        },
        step: 'Find one real person or group who needs this. Write down what they would miss without it.',
      },
      coin: {
        question: 'What could you be paid for?',
        placeholder: 'For example: technical support for small clinics',
        evidence: {
          market: 'People are paid for this work today.',
          paid: 'I have been paid for it, even once.',
          enough: 'I looked up what it pays, and it covers what I need.',
        },
        step: 'Read three real job postings for this work. Note the pay and what they ask for.',
      },
    },
    tellStep: 'Tell one person you trust what you are working toward.',
    needs: {
      poverty: 'No poverty',
      hunger: 'Zero hunger',
      health: 'Good health and well-being',
      education: 'Quality education',
      gender: 'Gender equality',
      water: 'Clean water and sanitation',
      energy: 'Affordable and clean energy',
      work: 'Decent work and economic growth',
      industry: 'Industry, innovation and infrastructure',
      inequality: 'Reduced inequalities',
      cities: 'Sustainable cities and communities',
      consumption: 'Responsible consumption and production',
      climate: 'Climate action',
      ocean: 'Life below water',
      land: 'Life on land',
      peace: 'Peace, justice and strong institutions',
      partnership: 'Partnerships for the goals',
    },
    // Free public sources for checking a need or a wage. Shown under Cause and Coin.
    sources: {
      cause: [{ label: 'Job outlook by occupation (US Bureau of Labor Statistics)', url: 'https://www.bls.gov/ooh/' }],
      coin: [
        { label: 'Pay by occupation (US Bureau of Labor Statistics)', url: 'https://www.bls.gov/ooh/' },
        { label: 'What each occupation involves (O*NET OnLine)', url: 'https://www.onetonline.org/' },
      ],
    },
  },

  // My Pride: friends added by QR code or link, with preset cheers. Nothing here may promise
  // an outcome, and cheers stay preset so no one can send a hurtful message.
  pride: {
    heading: 'MY PRIDE',
    intro: 'Walk with friends. Swap cards by QR code or link, follow how their lions grow, and send a cheer.',
    noName: 'A traveler',
    slot: (level: number, max: number) => `PRIDE: LEVEL ${level}/${max}`,
    slotNext: (needed: number) =>
      needed === 1 ? 'One more connection takes it to the next level.' : `${needed} more connections take it to the next level.`,
    slotFull: 'Your pride is at full strength.',
    tally: (friends: number, outreach: number) =>
      `Connections so far: ${friends} from friends, ${outreach} from outreach.`,

    logHeading: 'CONNECTIONS LOG',
    logIntro: 'A pride is built out in the world. Log outreach when you have really done it. RWR cannot see your LinkedIn or your email, so this is your own word, and it only works if it is true.',
    logKinds: {
      linkedin: 'Connected with someone on LinkedIn',
      message: 'Sent an email or message about a job',
      talk: 'Had a real conversation about the work',
      interview: 'Landed a job interview',
    },
    logWorth: { linkedin: '+1', message: '+1', talk: '+2', interview: '+2 and sparks' },
    logNoteLabel: 'Who was it? A first name or a role is enough.',
    logNotePlaceholder: 'For example: recruiter at a clinic group',
    logAdd: 'LOG IT',
    logPrivate: 'This log stays on your device. It is never part of your card.',
    logEmpty: 'Nothing logged yet.',
    logRemove: 'Remove',
    cheerRule: (n: number) =>
      `Each cheer earns ${n} ${n === 1 ? 'spark' : 'sparks'} for the wardrobe, once per friend per day, and only from someone in your pride.`,

    cardHeading: 'MY CARD',
    cardIntro: 'This is everything a friend sees. Nothing else you typed is shared.',
    cardWith: (name: string, lion: string) => `${name} and ${lion}`,
    power: (n: number, max: number) => `PRIDE POWER ${n}/${max}`,
    goal: 'Main goal:',
    goalReached: 'GOAL REACHED',
    goalOn: 'SHARE MY GOAL: ON',
    goalOff: 'SHARE MY GOAL: OFF',
    qrAlt: 'QR code for your pride card',
    qrHint: 'A friend points their phone camera at this code, or you send them the link.',
    copy: 'COPY MY LINK',
    share: 'SHARE',
    shareTitle: 'Join my pride on RWR',
    copied: 'Link copied. Send it to a friend.',
    copyFailed: 'Copying did not work here. Select the link below and copy it by hand.',

    addHeading: 'ADD A FRIEND',
    addIntro: "Scan a friend's code with your phone camera, or paste their link here.",
    addLabel: "Friend's link",
    addPlaceholder: 'Paste a pride link',
    addButton: 'ADD',
    addBad: 'That does not look like a pride link. Ask your friend to send it again.',
    addOwn: 'That is your own card.',
    addFull: 'Your pride is full. Say goodbye to a friend to make room.',

    incoming: (name: string, lion: string) => `${name} and their lion ${lion} want to join your pride.`,
    incomingYes: 'ADD TO MY PRIDE',
    incomingNo: 'NOT NOW',
    added: (name: string) => `${name} joined your pride.`,
    updated: (name: string) => `${name}'s card is up to date.`,
    cheerFrom: (name: string) => `${name} sent you a cheer:`,
    cheerClose: 'THANKS',

    friendsHeading: 'MY FRIENDS',
    friendsEmpty: 'No friends here yet. Share your card to start your pride.',
    asOf: (date: string) => `As of ${date}`,
    refreshHint: 'Cards refresh when a friend shares their link again or sends a cheer.',
    cheerButton: 'SEND A CHEER',
    cheerPick: (name: string) => `Pick a cheer for ${name}:`,
    cheerCancel: 'CANCEL',
    cheerCopied: (name: string) => `Cheer link copied. Send it to ${name}.`,
    cheerShareTitle: 'A cheer from RWR',
    remove: 'SAY GOODBYE',
    removeConfirm: (name: string) => `Remove ${name} from your pride? You can add them again with their link.`,
    removeYes: 'YES, REMOVE',
    removeNo: 'KEEP',
    cheers: {
      going: 'Keep going. I see the work you are putting in.',
      proud: 'Proud of you.',
      step: 'One small step today is enough.',
      back: 'I have your back on this trail.',
      rest: 'Rest counts too. Pick it back up tomorrow.',
    },

    receivedHeading: 'CHEERS FOR ME',
    receivedEmpty: 'Cheers from friends will show up here.',
    back: 'BACK TO UPGRADES',
  },

  roar: {
    heading: 'THE ROAR',
    noGoal: 'You have not set a main goal yet. What are you working toward?',
    goalLabel: 'My main goal',
    goalPlaceholder: 'For example: land my first design role',
    goalSave: 'SET GOAL',
    goalShown: 'Your main goal:',
    reachedQuestion: 'GOAL REACHED?',
    confirm: 'Are you ready to let Todah roar?',
    confirmYes: (sex: 'male' | 'female') => (sex === 'female' ? 'YES, LET HER ROAR' : 'YES, LET HIM ROAR'),
    confirmNo: 'NOT YET',
    rewardTitle: 'PRIDE LEADER',
    rewardBody: (name: string) =>
      name ? `You did this, ${name}. I only walked beside you.` : 'You did this. I only walked beside you.',
    replay: 'HEAR THE ROAR AGAIN',
    changeGoal: 'CHANGE GOAL',
    back: 'BACK TO UPGRADES',
    rewardAlt: 'Todah as a grown lion, roaring over a city skyline at sunset',
  },
}
