// Generated art. Do not edit by hand: the shapes were fitted to the seated sprite's outline.
//
// maneArt holds the mane at four sizes, on the sprite's grid (one cell is 3 sprite pixels).
// Size 0 is the cub's own bump of hair on top of the head. Size 1 is his first real hair: a
// narrow crest on top, like a mohawk. Size 2 widens it and adds ruffs beside the jaw and a
// small one on the chest, and size 3 is the full mane. The size follows the Mane upgrade's
// level. M is the mane colour and D its shade.
//
// foreheadTuft is the little lock of hair in the middle of his forehead, traced from the
// sprite pixel by pixel (three art pixels per cell), so it can take the mane's colour along
// with the hair on top.
//
// lionPendant is the chain's medallion, a lion's head in side view, at twice the grid's
// detail (two art pixels per cell).

export const maneArt: { x: number, y: number, rows: string[] }[] = [
  {
    x: 21,
    y: -1,
    rows: [
      '..DDDD.',
      '.DMMMM.',
      'D..M..D',
      'M.....M',
    ],
  },
  {
    x: 20,
    y: -5,
    rows: [
      '.....D...',
      '...DDM...',
      '...MMMD..',
      '..DMMMMD.',
      '.DMMMMMM.',
      '.MMMMMMMD',
      'DMMMMMMMM',
      'MMMMMMMMM',
      'MM..M..MM',
      '.M.....M.',
    ],
  },
  {
    x: 0,
    y: -4,
    rows: [
      '.......................D.D.........................',
      '.....................DDMDMDD.......................',
      '...................D.MMMMMMMD......................',
      '...................MDMMMMMMMMD.....................',
      '...................MMMMMMMMMMM.....................',
      '.................D.MMMMMMMMMMMDD...................',
      '................DMDMMM..M..MMMMM...................',
      '...............DMMM..M.....M.MMMDDD................',
      '..............DMMMM...........MMMMM................',
      '..............MM..M...........M.MMM................',
      '...............M.................M.................',
      '...................................................',
      '...................................................',
      '...................................................',
      '...................................................',
      '...................................................',
      '...................................................',
      '...................................................',
      'MM............................................MMD..',
      'MMM..........................................MMMD..',
      'DMMM.........................................MMMDD.',
      'DMMMM........................................MMMDMD',
      'DMMDMM.....................................MMDMMD..',
      '..DDMMMM.................................MMMMDD....',
      '...DMMMMM................................MMMMMD....',
      '...DMMDMM..............................MMMDMD......',
      '...DMMDMM..............................MMMDMD......',
      '...DMMDMM..............................MMMDMD......',
      '....DMDMMM.............................MMMDMD......',
      '....DMMMMM.............................MMMMMD......',
      '.....DDMMMM...........................MMMMDD.......',
      '.......DMDMM.........................MMDMD.........',
      '..........DMM.......................MMD............',
      '...................................................',
      '...................................................',
      '...............DDMMMMMMMMMMMMMMMMD.................',
      '................DDMMMMMMMMMMMMMMD..................',
      '.................DDMDMMMDMMMDMMD...................',
      '...................DDMMMDMMMDD.....................',
      '....................DDMMDMMMD......................',
      '.......................D.D.........................',
    ],
  },
  {
    x: 0,
    y: -5,
    rows: [
      '.......................D.D.........................',
      '.....................DDMDMDD.......................',
      '...................D.MMMMMMMD......................',
      '...................MDMMMMMMMMD.....................',
      '...................MMMMMMMMMMM.D...................',
      '.................DDMMMMMMMMMMMDM...................',
      '................DMMMMMMMMMMMMMMM.D.................',
      '.............D.DMMMMMMMMMMMMMMMMDM.DD..............',
      '............DMDMMMMMMM..M..MMMMMMMDMM..............',
      '............MMMMMMM..M.....M.MMMMMMMM..............',
      '............MMMMMMM...........MMMMMMM..............',
      '............M.MM..M...........M.MMM.M..............',
      '...............M.................M.................',
      '...................................................',
      '...................................................',
      '...................................................',
      '...................................................',
      'MM.............................................MMMD',
      'MM............................................MMDMM',
      'MM............................................MMDMM',
      'MMM..........................................MMMMMM',
      'DMMM.........................................MMMDMM',
      'DMMMM........................................MMMDMM',
      'DMMDMM.....................................MMDMMDMM',
      'DMMDMMMM.................................MMMMDMMDD.',
      'DMMMMMMMM................................MMMMMMMMD.',
      'DMMDMMDMM..............................MMMDMMDMD...',
      'DMMDMMDMM..............................MMMDMMDMD...',
      'DMMDMMDMM..............................MMMDMMDMD...',
      '.DMDMMDMMM.............................MMMDMMDMD...',
      '.DMMMMMMMM.............................MMMMMMMMD...',
      '..DDMMDMMMM...........................MMMMDMMDD....',
      '...DMMDMMDMM.........................MMDMMDMMD.....',
      '....DMDMMDMMM.......................MMMDMMDMD......',
      '.....DDMMDMMMM.....................................',
      '........DMMDDMMMMMMMMMMMMMMMMMMMMMMMMD.............',
      '...........DDDMMMMMMMMMMMMMMMMMMMMMMD..............',
      '.............DDMDMMMDMMMDMMMDMMMDMMD...............',
      '.............DDMDMMMDMMMDMMMDMMMDMMD...............',
      '..............DDDMMMDMMMDMMMDMMMDMD................',
      '...............DDMMMDMMMDMMMDMMMDD.................',
      '................DDMMMMMMMMMMMMMMD..................',
      '.................DDMDMMMDMMMDMMD...................',
      '.................DDMDMMMDMMMDMMD...................',
      '..................DDDMMMDMMMDMD....................',
      '...................DDMMMDMMMDD.....................',
      '....................DDMMDMMMD......................',
      '.....................DDMMMMD.......................',
      '.......................D.D.........................',
    ],
  },
]

export const foreheadTuft: { x: number, y: number, cell: number, rows: string[] } = {
  x: 57 / 3,
  y: 13 / 3,
  cell: 1 / 3,
  rows: [
    'DDDDDMMMDDDMDDDDMM.......',
    'DDDDDMDDDDDDDDDDDM.......',
    'DDDDDMMMDDDDDDDDDM.......',
    'DDDDDMMMDDDDDDDDDM.......',
    'DDDDDM.MMMMMMMMMM........',
    'DDDDM....................',
    'DDDDM....................',
    'DDDDM....................',
    'DDDDM....................',
    'MMMMMMDM..........MMMMM..',
    '....MDDD..........MDDDM..',
    '....MDDD..........MDDDM..',
    '....MDDD..........MDDDM..',
    '....MMMM..........MDDDM..',
    '........MMDDDM....MDDMM..',
    '........MDDDDM....MDDDM..',
    '........MDDDDM....MDDM...',
    '........MMMDMM.M.MMDDD...',
    '............MMMMMMMMMM...',
    '............MMDMMM.......',
    '............MMMMMM.......',
    '............MMMMMM.......',
    '............MMMMMM.......',
    '.........................',
  ],
}

export const lionPendant: string[] = [
  '........RRRRRRRR........',
  '......RRRRRRRRRRRR......',
  '....RRRKMMMMDMKKKRRR....',
  '...RRRMMMMDMMMMDKKRRR...',
  '..RRKMMMDMMMMGGGGKKKRR..',
  '..RRMMDMMMMDGGGGGGKKRR..',
  '.RRKDMMMMDMGGYYYGGGKKRR.',
  '.RKMMMMDMMMGYYYYYGGGKKR.',
  'RRKMMDMMMMGGYYEYYYGGKKRR',
  'RRKDMMMMDMGGYYYYYYYGGKRR',
  'RRKMMMDMMMGGYYYYYYYYEERR',
  'RRKMDMMMMDMGGYYYYYYYYERR',
  'RRKMMMMDMMMGGYYYYYYYYKRR',
  'RRKKMDMMMMDMGGYYYEEEEKRR',
  '.RKKMMMMDMMMGGGYYYYYKKR.',
  '.RRKKMDMMMMDMGGGYYYKKRR.',
  '..RRKMMMMDMMMMGGGKKKRR..',
  '..RRKKMDMMMMDMMMKKKKRR..',
  '...RRRKMMMDMMMMKKKRRR...',
  '....RRRKKMMMMKKKKRRR....',
  '......RRRRRRRRRRRR......',
  '........RRRRRRRR........',
]
